sky:
  datasource:
    driver-class-name: 
    host: 
    port: 
    database: 
    username: 
    password: 
  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 

  redis:
    host: localhost
    port: 6379
    password:
    database: 0

  wechat:
    appid: wxce35e18e4def0d60
    secret: f6fd42683233702e18875682d73fbfd5
