server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 47.93.145.171:8848
    gateway:
      routes:
        - id: product # 路由规则id，自定义，唯一
          uri: lb://product-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/dish/**,/admin/setmeal/**,/admin/category/**,/admin/shop/**,
                   /user/dish/**,/user/setmeal/**,/user/category/**,/user/shop/** # 这里是以请求路径作为判断规则
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/employee/**,/user/addressBook/**,/user/user/** # 这里是以请求路径作为判断规则
        - id: trade # 路由规则id，自定义，唯一
          uri: lb://trade-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/order/**,/user/order/**,/user/shoppingCart/**,/ws/**  # 这里是以请求路径作为判断规则
        - id: pay # 路由规则id，自定义，唯一
          uri: lb://pay-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/notify/**  # 这里是以请求路径作为判断规则
        - id: statistic # 路由规则id，自定义，唯一
          uri: lb://statistic-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/workspace/**,/admin/report/**  # 这里是以请求路径作为判断规则
        - id: ai # 路由规则id，自定义，唯一
          uri: lb://ai-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/admin/chat/**  # 这里是以请求路径作为判断规则
      default-filters:
        - AddRequestHeader=truth, anyone long-press like button will be rich
  main:
    web-application-type : reactive
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication
  auth:
    excludePaths:
      - /doc.html
      - /admin/employee/login
      - /user/user/login
      - /user/shop/status
      - /ws/**
      - /webjars/**
      - /swagger-ui/**
      - /v3/api-docs/**

